# Generated by Django 6.0.6 on 2026-08-18 19:28

import books.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('author', models.CharField(max_length=200, verbose_name='Autor(es)')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('file', models.FileField(help_text='Solo PDF o ePub.', upload_to=books.models.book_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'epub']), books.models.validate_book_file_size], verbose_name='Archivo')),
                ('license_type', models.CharField(choices=[('PD', 'Dominio público'), ('CC', 'Creative Commons'), ('OR', 'Obra original del usuario')], max_length=2, verbose_name='Licencia')),
                ('license_detail', models.CharField(blank=True, help_text='Ejemplo: CC BY-NC 4.0', max_length=200, verbose_name='Detalle de licencia')),
                ('rights_declaration', models.TextField(blank=True, help_text='Obligatoria para obras originales.', verbose_name='Declaración de derechos')),
                ('status', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Rechazado')], default='P', max_length=1, verbose_name='Estado')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='Comentario del revisor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_books', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_books', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('book', 'user'), name='unique_rating_per_book_and_user'), models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='rating_score_between_1_and_5')],
            },
        ),
    ]
