# Generated by Django 6.0.6 on 2026-08-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Rechazado'), ('D', 'REPORTADO')], default='P', max_length=1, verbose_name='Estado'),
        ),
    ]
