# Generated by Django 6.0.6 on 2026-09-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Author(s)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='license_type',
            field=models.CharField(choices=[('PD', 'Public domain'), ('CC', 'Creative Commons'), ('OR', 'Original work by the user')], max_length=2, verbose_name='Licencia'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Aproved'), ('R', 'Rejected'), ('E', 'Reported')], default='P', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
