# Generated by Django 6.0.6 on 2026-09-26 20:49

import books.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_cover_alter_book_author_alter_book_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(help_text='Onli PDF or ePub.', upload_to=books.models.book_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'epub']), books.models.validate_book_file_size], verbose_name='Archive'),
        ),
        migrations.AlterField(
            model_name='book',
            name='license_detail',
            field=models.CharField(blank=True, help_text='Example: CC BY-NC 4.0', max_length=200, verbose_name='License details'),
        ),
        migrations.AlterField(
            model_name='book',
            name='license_type',
            field=models.CharField(choices=[('PD', 'Public domain'), ('CC', 'Creative Commons'), ('OR', 'Original work by the user')], max_length=2, verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Revision date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_books', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reviewer_comment',
            field=models.TextField(blank=True, verbose_name="Reviewer's comment"),
        ),
        migrations.AlterField(
            model_name='book',
            name='rights_declaration',
            field=models.TextField(blank=True, help_text='Mandatory for original works.', verbose_name='Statement of Rights'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Aproved'), ('R', 'Rejected'), ('E', 'Reported')], default='P', max_length=1, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Punctuation'),
        ),
    ]
